<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\4.Domain\Domain.csproj" />
    <ProjectReference Include="..\5.Shared\Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Events\Agent\Contracts\Queries\" />
    <Folder Include="Events\Agent\Handlers\Queries\" />
    <Folder Include="Events\User\Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Mapster" Version="10.0.11" />
    <PackageReference Include="Mapster.DependencyInjection" Version="10.0.11" />
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
  </ItemGroup>

</Project>
